# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 13:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemoapp', '0003_auto_20190713_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancer',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
