# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemoapp', '0004_auto_20190713_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancer',
            name='cancer',
        ),
        migrations.AddField(
            model_name='cancer',
            name='illness',
            field=models.CharField(choices=[('Cervical', 'Cervical'), ('Breast', 'Breast'), ('Leukemia', 'Leukemia')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
